apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.deployment.annotations }}
  annotations:
    {{- toYaml .Values.deployment.annotations | nindent 4 }}
  {{- end }}
  labels:
    app:  {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      {{- if .Values.deployment.pod.annotations }}
      annotations:
        {{- toYaml .Values.deployment.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.name }}
          image: {{- printf " %s:%s" .Values.image.repository  .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: {{ .Values.name }}
            - name: PORT
              value: "8443"
            - name: CERT_FILE
              value: /etc/webhook/certs/tls.crt
            - name: KEY_FILE
              value: /etc/webhook/certs/tls.key
            {{- with .Values.deployment.pod.container.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
          - name: tls
            mountPath: /etc/webhook/certs
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tlsSecretName }}
